import{S as h,i as c,a as g}from"./assets/vendor-D1mpe0f-.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const f of r.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&d(f)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function d(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const b=document.querySelector("#search-form"),p=document.querySelector("#gallery"),n=document.querySelector("#loader"),i=document.querySelector("#load-more");let l="",a=1;const u=40;let L=new h(".gallery a",{captionsData:"alt",captionDelay:250});b.addEventListener("submit",w);i.addEventListener("click",S);async function w(o){if(o.preventDefault(),l=o.currentTarget.elements.searchQuery.value.trim(),!!l){a=1,p.innerHTML="",i.style.display="none",n.style.display="block";try{const t=await y(l,a);if(n.style.display="none",t.hits.length===0){c.error({message:"Sorry, there are no images matching your search query. Please, try again!",position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff"});return}m(t.hits),t.totalHits>u&&(i.style.display="block")}catch{n.style.display="none",c.error({message:"Bir şeyler ters gitti!",position:"topRight"})}}}async function S(){a+=1,i.style.display="none",n.style.display="block";try{const o=await y(l,a);m(o.hits),n.style.display="none",v();const t=Math.ceil(o.totalHits/u);a>=t?c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"#4e75ff",messageColor:"#fff"}):i.style.display="block"}catch{n.style.display="none",c.error({message:"Görseller yüklenirken hata oluştu!",position:"topRight"})}}async function y(o,t){return(await g.get("https://pixabay.com/api/",{params:{key:"56616492-365663f16d6efa67721cffd28",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:u}})).data}function m(o){const t=o.map(s=>`
      <a href="${s.largeImageURL}" class="photo-card">
        <img src="${s.webformatURL}" alt="${s.tags}" loading="lazy" />
        <div class="info">
          <p class="info-item"><b>Likes</b> ${s.likes}</p>
          <p class="info-item"><b>Views</b> ${s.views}</p>
          <p class="info-item"><b>Comments</b> ${s.comments}</p>
          <p class="info-item"><b>Downloads</b> ${s.downloads}</p>
        </div>
      </a>`).join("");p.insertAdjacentHTML("beforeend",t),L.refresh()}function v(){const{height:o}=p.firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
